In [ ]:
# importing tensorflow  
import tensorflow as tf


In [ ]:
print(tf.__version__)

2.7.0


In [ ]:
# creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# checking dimentional of the tesor
scalar.ndim

0

In [ ]:
# creating vector
vector = tf.constant([2,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# creating matrix
matrix = tf.constant([[2,6],
                      [4,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [4, 7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix_1 = tf.constant([[10,4,5],
                       [2,4,6]], dtype=tf.float16)
matrix_1


<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  4.,  5.],
       [ 2.,  4.,  6.]], dtype=float16)>

In [ ]:
type(matrix_1)


tensorflow.python.framework.ops.EagerTensor

In [ ]:
matrix_1.ndim

2

In [ ]:
# creating tensor
tensor = tf.constant([[[1,2,4],
                       [3,5,6]],
                      [[3,5,7],
                       [7,9,6]],
                      [[4,5,7],
                       [5,7,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [3, 5, 6]],

       [[3, 5, 7],
        [7, 9, 6]],

       [[4, 5, 7],
        [5, 7, 8]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

Scalar:  a single no
Vector: a no. with direction(eg. wind speed and direction)
Matrix: a 2d array of no
Tensor: a nd array of no. where 0<=n>=n

**Creating tensor with tf.variable**

In [ ]:
tensor_changable = tf.Variable([10,7])
tensor_unchangable = tf.constant([10,7])
tensor_changable, tensor_unchangable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
tensor_changable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tensor_changable[0] = 8

TypeError: ignored

In [ ]:
tensor_changable[0].assign(6)

In [ ]:
tensor_unchangable[0].assign(5)

**Creating random tensors**

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,4))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,4))
random_1, random_2, random_1 == random_1

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707, -0.06378496,  0.92800784],
        [-0.6039789 , -0.1766927 ,  0.04221033,  0.29037967]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

**Shuffling order in tensor**

In [ ]:

not_sh = tf.constant([[2,4,6],
                      [4,7,8],
                      [6,8,9]])
not_sh.ndim

2

In [ ]:
sh = tf.random.shuffle(value=not_sh, seed=None, name=None)

In [ ]:
sh

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 9],
       [2, 4, 6],
       [4, 7, 8]], dtype=int32)>

In [ ]:
# diff order each time - only op
sh_1 = tf.random.shuffle(value=not_sh, seed=42, name=None)
sh_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 7, 8],
       [6, 8, 9],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# global level + op level random seed -> same order each time (rule 4)
tf.random.set_seed(42)
tf.random.shuffle(not_sh, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [4, 7, 8],
       [6, 8, 9]], dtype=int32)>

**Other ways to make tensors**

In [ ]:
 tf.ones([2,5])

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
 tf.zeros([2,5])

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# numpy arrays to tensors
import numpy as  np
n = np.arange(1,25,dtype=np.int32)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(n, shape=(2,3,4))
B = tf.constant(n)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

**Getting more info from tensors**
 * Shape - .shape
 * Rank - .ndim
 * Axis - tensor[0]
 * Size - tf.size(tensor)

In [ ]:
# rank 4 tensor
t4 = tf.zeros(shape=[2,3,4,5])
t4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
t4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
t4.shape, t4.ndim, tf.size(t4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# getting various attributes of our tensor
print("data type:", t4.dtype)
print("rank:", t4.ndim)
print("shape:", t4.shape)
print("elements along 0 axis:", t4.shape[0])
print("elements along last axis:", t4.shape[-1])
print("total ele in tensor:", tf.size(t4).numpy())

data type: <dtype: 'float32'>
rank: 4
shape: (2, 3, 4, 5)
elements along 0 axis: 2
elements along last axis: 5
total ele in tensor: 120


Indexing tensors
- just like python list

In [ ]:
t = [1,2,4,5]
t[:2]

[1, 2]

In [ ]:
t4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
t4.shape

TensorShape([2, 3, 4, 5])

In [ ]:
t4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
t4[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
t4[:,:1,:,:1]

<tf.Tensor: shape=(2, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
t2 = tf.constant([[1,2],
                  [3,5]])
t2, t2.ndim, t2.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 5]], dtype=int32)>, 2, TensorShape([2, 2]))

In [ ]:
t2[1:,-1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [ ]:
# add extra dimension in r2 tensor
t3 = t2[...,tf.newaxis]
t3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [5]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(t2, axis=-1) # at last


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [5]]], dtype=int32)>

In [ ]:
tf.expand_dims(t2, axis=0) # at first

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 5]]], dtype=int32)>

**Manipulating tensors(Tensors Op)**

In [ ]:
# +,-,*,/
ten = tf.constant([[19,3],[3,6]])

In [ ]:
ten + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 13],
       [13, 16]], dtype=int32)>

In [ ]:
# original tensor is unchanged
ten - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17,  1],
       [ 1,  4]], dtype=int32)>

In [ ]:
ten * 2
# or
tf.multiply(ten, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[190,  30],
       [ 30,  60]], dtype=int32)>

In [ ]:
ten // 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 1],
       [1, 2]], dtype=int32)>

In [ ]:
ten

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19,  3],
       [ 3,  6]], dtype=int32)>

**Matrix multiplication**
- dot product - @/matmul/tensordot

Rules to fulfill for matrix mul
  - inner dim must match
  - resulting matrix must have the same shape as outer dim (1,2),(3,5) = (1,5)

In [ ]:
te = tf.constant([[10,7],
                  [6,5]])
tens = tf.constant([[1,2],
                  [2,4]])

te

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  5]], dtype=int32)>

In [ ]:
tf.matmul(te,tens)
# or
te @ tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 48],
       [16, 32]], dtype=int32)>

In [ ]:
t1 = tf.constant([[1,2],
                  [2,4],
                  [4,7]])
t2 = tf.constant([[11,22],
                  [22,4],
                  [54,17]])


In [ ]:
t1 @ t2

InvalidArgumentError: ignored

In [ ]:
# to solve this error
# change shape of t2
tf.reshape(t2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 22, 22],
       [ 4, 54, 17]], dtype=int32)>

In [ ]:
t1 @ tf.reshape(t2,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 19, 130,  56],
       [ 38, 260, 112],
       [ 72, 466, 207]], dtype=int32)>

In [ ]:
tf.matmul(t1,tf.reshape(t2,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 19, 130,  56],
       [ 38, 260, 112],
       [ 72, 466, 207]], dtype=int32)>

In [ ]:
# tranpose - row col, col row
t1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [4, 7]], dtype=int32)>

In [ ]:
tf.transpose(t1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 4, 7]], dtype=int32)>

**Changing datatype of the tensors**

In [ ]:
B = tf.constant([1,3,5,6])
B
B.dtype

tf.int32

In [ ]:
C = tf.constant([1.2,3.4,5.7,3.6])
C.dtype

tf.float32

In [ ]:
# change from float32 to float16 (reduced precision)
C = tf.cast(C,dtype=tf.float16)
C

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1.2, 3.4, 5.7, 3.6], dtype=float16)>

In [ ]:
# change from int32 to float16 (reduced precision)
B = tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 3., 5., 6.], dtype=float16)>

**Aggregate tesors**
  -Min
  -Max
  -Sum
  -Mean
  -Standard Deviation

In [ ]:
c = tf.constant([-1,3,-3])
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1,  3, -3], dtype=int32)>

In [ ]:
tf.abs(c)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 3], dtype=int32)>

In [ ]:
e = tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([72, 40, 91, 14, 53,  6, 46, 13, 59, 38, 86, 95, 55, 45, 46,  5, 53,
       96,  7, 57, 29, 64, 74, 18, 84, 48, 44, 46, 11, 90, 97, 54, 43, 16,
       63, 24, 80, 13, 34, 70, 88, 28, 79, 90,  8, 91, 70, 61, 14, 13])>

In [ ]:
#Min    
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
#Max
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#Mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
#Sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2521>

In [ ]:
# variance
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=826>

In [ ]:
# std 
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=28.744453>

**Find pos min and max**

In [ ]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# pos max - argmax-indice
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# pos max - argmax-index
tensor[tf.argmax(tensor)]
#or
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# pos min - argmax-index
tensor[tf.argmin(tensor)]
#or
tf.reduce_min(tensor)


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing the tensors (removing all single dimensions)**

In [ ]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
#squeeze
tensor_s = tf.squeeze(tensor)
tensor_s.shape

TensorShape([50])

One-hot encoding

In [ ]:
l = [0,1,2,3] # rgbp

In [ ]:
tf.one_hot(l, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Custom values for one hot encoding

In [ ]:
tf.one_hot(l, depth=4, on_value="yes", off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

Squaring, log, square root

In [ ]:
d = tf.range(1,10)
d

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(d)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Square root
tf.sqrt(tf.cast(d, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Log
tf.math.log(tf.cast(d, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensors and numpy**

In [ ]:
j = tf.constant(np.array([1.7,2.5,2.7]))
j, type(j) # tensor
# tensor to numpy
type(j.numpy())

numpy.ndarray

In [ ]:
j[0]

<tf.Tensor: shape=(), dtype=float64, numpy=1.7>

In [ ]:
j.numpy()[0]

1.7